import React, { useEffect, useState } from 'react';
import { Card } from '../components/ui/Card.tsx';
import { XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Area, ComposedChart, Line } from 'recharts';
import { X } from 'lucide-react';
import { api } from '../services/api.ts';
import './ForecastExplorer.css';

export const ForecastExplorer: React.FC = () => {
  const [data, setData] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [skuSearch, setSkuSearch] = useState('SKU-8921-ULTRA-BOOST-WHITE');
  const [isOverrideModalOpen, setIsOverrideModalOpen] = useState(false);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const forecast = await api.forecasting.getExplorerData();
        
        // Match the chart look from the mockup by transforming the chartData specifically for Recharts Area
        const transformedChartData = forecast.chartData.map((d: any, i: number) => ({
          name: d.date,
          actual: i < 5 ? d.actual : null,
          predicted: i >= 4 ? (d.forecast || d.actual) : null,
          ci_lower: i >= 4 ? d.lower : null,
          ci_upper: i >= 4 ? d.upper : null,
        }));

        setData({ ...forecast, chartData: transformedChartData });
      } catch (error) {
        console.error("Failed to load forecast explorer data", error);
      } finally {
        setIsLoading(false);
      }
    };
    fetchData();
  }, []);

  return (
    <div className="animate-fade-in mb-6">
      {/* Filters Bar */}
      <Card className="mb-6 p-6">
        <div className="forecast-filters">
          <div className="filter-group">
            <div className="filter-item">
              <label className="filter-label">Product Category</label>
              <select className="filter-select">
                <option>Footwear & Running</option>
                <option>Apparel</option>
                <option>Accessories</option>
              </select>
            </div>
            
            <div className="filter-item">
              <label className="filter-label">Location / Store</label>
              <select className="filter-select">
                <option>E-Commerce Warehouse</option>
                <option>Downtown Flagship</option>
              </select>
            </div>
            
            <div className="filter-item">
              <label className="filter-label">SKU Identifier</label>
              <div className="filter-input-wrapper">
                <input 
                  type="text" 
                  className="filter-input" 
                  value={skuSearch}
                  onChange={(e) => setSkuSearch(e.target.value)}
                />
                <button className="clear-input-btn" onClick={() => setSkuSearch('')}>
                  <X size={14} />
                </button>
              </div>
            </div>
          </div>
          
          <div className="filter-group" style={{ flex: 'none' }}>
            <div className="filter-item">
              <label className="filter-label">Forecast Horizon</label>
              <div className="horizon-toggle">
                <button className="horizon-btn">7d</button>
                <button className="horizon-btn">14d</button>
                <button className="horizon-btn active">28d</button>
              </div>
            </div>
            
            <div className="filter-item">
              <label className="filter-label">ML Engine Selector</label>
              <select className="ml-engine-select">
                <option>TFT (Temporal Fusion)</option>
                <option>LightGBM</option>
                <option>ARIMA Baseline</option>
              </select>
            </div>
          </div>
        </div>
      </Card>

      {/* Main Chart */}
      <Card className="mb-6 p-6">
        <div className="chart-header">
          <div className="chart-title-area">
            <h3>Historical Demand & Temporal Fusion Forecast</h3>
            <p>Light teal band indicates the 90% confidence predictive interval generated by TFT engine.</p>
          </div>
          <div className="chart-legend">
            <div className="legend-item"><div className="legend-line-actual"></div> Historical Sales</div>
            <div className="legend-item"><div className="legend-line-predicted"></div> Point Forecast</div>
            <div className="legend-item"><div className="legend-box-horizon" style={{backgroundColor: '#e6f6f4', opacity: 1}}></div> 90% Confidence Interval</div>
          </div>
        </div>
        
        <div className="chart-area" style={{ height: '300px' }}>
          <div className="forecast-horizon-bg" style={{ width: '40%', backgroundColor: '#f0fdfa', opacity: 0.5 }}></div>
          {isLoading || !data ? (
            <div className="flex items-center justify-center h-full text-[var(--text-secondary)]">Loading forecast data...</div>
          ) : (
            <div className="chart-wrapper">
              <ResponsiveContainer width="100%" height="100%">
                <ComposedChart data={data.chartData} margin={{ top: 20, right: 0, left: 0, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--border-color)" />
                  <XAxis dataKey="name" stroke="var(--text-secondary)" axisLine={false} tickLine={false} tick={{fontSize: 10}} />
                  <YAxis hide />
                  <Tooltip 
                    cursor={{stroke: '#cbd5e1', strokeWidth: 1, strokeDasharray: '5 5'}}
                    contentStyle={{ backgroundColor: 'var(--bg-secondary)', borderColor: 'var(--border-color)', borderRadius: '8px', boxShadow: 'var(--shadow-md)' }}
                  />
                  
                  <Area type="monotone" dataKey="ci_upper" fill="#e6f6f4" stroke="none" />
                  <Area type="monotone" dataKey="ci_lower" fill="#ffffff" stroke="none" />
                  
                  <Line type="monotone" dataKey="actual" stroke="#475569" strokeWidth={2} dot={false} activeDot={{ r: 4 }} />
                  <Line type="monotone" dataKey="predicted" stroke="#0d9488" strokeWidth={2} strokeDasharray="4 4" dot={false} activeDot={{ r: 4 }} />
                </ComposedChart>
              </ResponsiveContainer>
            </div>
          )}
        </div>
        
        <div className="override-section">
          <div className="override-info">
            <h4 className="override-title">Manual Forecast Override</h4>
            <p className="override-desc">Apply a temporary business override adjustment to the projected baseline demand for this SKU.</p>
            <div className="override-current">
              <span className="override-label">Current predicted demand</span>
              <span className="override-value">1,420 units</span>
            </div>
          </div>
          <div className="override-action">
            <span className="override-status">Manual Override Applied</span>
            <button className="override-btn" onClick={() => setIsOverrideModalOpen(true)}>Override Forecast</button>
          </div>
        </div>
      </Card>

      {!isLoading && data && (
        <div className="grid-cols-2">
          {/* Stats */}
          <Card className="p-6">
            <h3 className="chart-title-area" style={{ marginBottom: '1rem', fontSize: '1.125rem', fontWeight: 700, fontFamily: 'Outfit' }}>Forecast Performance Stats</h3>
            <p className="engine-desc">
              Engine: Temporal Fusion Transformer optimized for seasonal fashion runs.
            </p>
            
            <div className="stats-list">
              <div className="stat-item">
                <span className="stat-label">Predicted 28d Demand</span>
                <span className="stat-value">{data.stats.predictedDemand}</span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Recommended Safety Stock</span>
                <span className="stat-value">{data.stats.safetyStock}</span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Optimal Reorder Point</span>
                <span className="stat-value">{data.stats.reorderPoint}</span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Active Model MASE</span>
                <span className="stat-value" style={{display: 'flex', gap: '0.25rem'}}>
                  <strong>{data.stats.mase}</strong>
                  <span className="text-teal">(Excellent)</span>
                </span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Confidence Interval (90%)</span>
                <span className="stat-value">{data.stats.ci}</span>
              </div>
            </div>
          </Card>

          {/* Matrix */}
          <Card className="p-6">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1.5rem' }}>
              <h3 className="chart-title-area" style={{ fontSize: '1.125rem', fontWeight: 700, fontFamily: 'Outfit' }}>Forecast Schedule Matrix (Next 7 Days)</h3>
              <span style={{ fontSize: '0.625rem', fontWeight: 700, color: '#0d9488', letterSpacing: '0.05em' }}>OCT 24 - OCT 30</span>
            </div>
            
            <div className="matrix-table">
              <div className="matrix-header-row">
                <div className="matrix-col-header matrix-col-1">Date</div>
                <div className="matrix-col-header matrix-col-2">Predicted Demand</div>
                <div className="matrix-col-header matrix-col-3">Lower Bound (90%)</div>
                <div className="matrix-col-header matrix-col-4">Upper Bound (90%)</div>
                <div className="matrix-col-header matrix-col-5 text-right">Spike Danger</div>
              </div>
              
              {data.scheduleMatrix.map((row: any, idx: number) => (
                <div className="matrix-row" key={idx}>
                  <div className="matrix-cell matrix-col-1 font-bold">{row.date}</div>
                  <div className="matrix-cell matrix-col-2 text-teal">{row.demand} units</div>
                  <div className="matrix-cell matrix-col-3">{row.lower} units</div>
                  <div className="matrix-cell matrix-col-4">{row.upper} units</div>
                  <div className={`matrix-cell matrix-col-5 text-right ${row.spikeColor}`}>{row.spike}</div>
                </div>
              ))}
            </div>
          </Card>
        </div>
      )}

      {/* Override Modal */}
      {isOverrideModalOpen && (
        <div className="modal-overlay">
          <div className="modal-content">
            <button className="modal-close" onClick={() => setIsOverrideModalOpen(false)}><X size={16} /></button>
            <h2 className="modal-title">Manual Forecast Override</h2>
            <p className="modal-subtitle">SKU-8921-ULTRA-BOOST-WHITE • E-Commerce Warehouse • 28d Horizon</p>
            
            <div className="modal-form-group mt-4">
              <label>Current predicted demand</label>
              <div className="modal-readonly-input">
                <span className="text-xl font-bold">1,420 units</span>
              </div>
            </div>
            
            <div className="modal-form-group">
              <label>Adjusted Forecast</label>
              <div className="modal-input-wrapper">
                <input type="text" defaultValue="1,480" className="modal-input" />
                <span className="modal-input-suffix">units</span>
              </div>
            </div>
            
            <div className="modal-form-group">
              <label>Override reason category</label>
              <select className="modal-select">
                <option>Seasonal Adjustment</option>
                <option>Promotional Event</option>
                <option>Supply Chain Disruption</option>
              </select>
            </div>
            
            <div className="modal-form-group">
              <label>Reason for Override</label>
              <textarea className="modal-textarea" placeholder="Enter justification for manual adjustment..."></textarea>
            </div>
            
            <div className="modal-info-banner">
              <div className="banner-dot"></div>
              <span>Override will be logged and tracked for model accuracy comparison.</span>
            </div>
            
            <div className="modal-actions">
              <button className="modal-btn-cancel" onClick={() => setIsOverrideModalOpen(false)}>Cancel</button>
              <button className="modal-btn-apply" onClick={() => setIsOverrideModalOpen(false)}>Apply Override</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
